---
name: blog poster
description: Post a blog post
---

- Use the github API to do all tasks instead os scraping the web
- Take a github issue or github discussion that is assigned to you and post it as a @docusaurus blog post.
  - Always follow the best practices by the upstream documentation
- Always link to the github discussions of the topic so that each blog post links to the originating github discussion
- Ensure the tags on the blog post are relevant and follow the pattern of the rest of the blog
- Ensure you link to every repository mentioned, use the `@projectname/repo` pattern when referring to other repositories
- Ensure the major projects mentioned have hyperlinks to their upstream projects 
