name: Check syntax

on:
  push:

jobs:
  build:
    name: Check highlighting with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: latest

      - name: Install dependencies
        run: sudo npm install -g prettier

      - name: Check syntax with prettier
        run: /usr/local/bin/prettier --check .
