name: Validate Renovate

on:
  pull_request:
    paths:
      - "**/renovate.json"
      - "**/renovate.json5"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict
