name: Update Images Page

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-images.yml'
      - 'scripts/update-images.sh'

permissions:
  contents: write

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch image data and update page
        run: |
          chmod +x scripts/update-images.sh
          ./scripts/update-images.sh

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/images.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update images page"
            git push
          fi
